services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack_bot
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - TARGET_TAG=${TARGET_TAG}
      - TARGET_CHANNEL=${TARGET_CHANNEL}
      - DEBUG_MODE=${DEBUG_MODE}
      - ADMIN_PW=${ADMIN_PW}
      - NEW_API_CHAT_IDS=${NEW_API_CHAT_IDS}
      - OLD_API_CHAT_IDS=${OLD_API_CHAT_IDS}
    volumes:
      - ./logs:/app/logs
    networks:
      - slack_bot

networks:
  slack_bot:
    driver: bridge